
set expandtab
set shiftwidth=2
set tabstop=2

set number

set ruler
set showmode

set hlsearch
set incsearch

set nocompatible
set backspace=indent,eol,start


autocmd FileType make setlocal noexpandtab

" replace
" %s/\s\+$//g
hi TrailingSpace ctermbg=red
match TrailingSpace /\s\+$/

let mapleader=","
filetype plugin on
syntax on

"set verbosefile=aa.txt
"set shell=tcsh\ -f

